Added Author In-Group to list of Tasks, Fixed Checkbox tasks, Updated Test Behavior
JHU-CLSP/turk-instructions pull request #72
Opened 2023-09-14 22:40 UTC by klxu03

I went ahead and added in the Author In-Group Analysis Phrase Classification 2 into the list of allowed tasks. That didn't work out of the box (as I had hoped from a previous PR of updating the column names) and found the issue was due to our program not compatible with checkbox logic if the values were "True" or "False". The only attribute on the checkbox was "on".

I initially considered changing the logic in actions.py to check if the CSV value was True, then I would check the checkbox. Although this led to checking happening, the evaluator score was still 0% since it wasn't an exact match.  Thus, I decided to fix this by updating the actual CSV files (which we will need to continue to do for checkbox tasks). I modified the cleanup python script to run through the csv and turn all instances of True into "on" and False into "", an empty string which was the correct value for the evaluator.

I also updated the test behavior to first run through the tests without any print statements logging since those made the tests run slower. If an issue was encountered, it would go ahead and re-run all the test instances with logging
![image](https://github.com/JHU-CLSP/turk-instructions/assets/48634131/08f5dc36-8a8b-48a9-91bd-e409f25b46cc)

Also I made a slight change to the issue of trying to select nan from a list of checkboxes? However, it shouldn't have fixed it as it should trigger the else statement and throw an exception (but that was not thrown here). May need to look into that again

2023-09-14 22:42 UTC, danyaljj commented on tasks/Author In-Group Analysis Phrase Classification 2/.DS_Store
We should drop this?

2023-09-14 22:59 UTC, danyaljj requested changes
LGTM except one extra file that need to be dropped.

2023-09-14 23:55 UTC, klxu03 commented on tasks/Author In-Group Analysis Phrase Classification 2/.DS_Store
Yeah should drop! My bad it slipped through
@danyaljj

2023-09-15 00:18 UTC, danyaljj approved these changes

2023-09-15 00:18 UTC, merged